a = input('Digite algo: ')
print('Tipo primitivo é', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())

print('----------------------------------')

print(f'Tipo primitivo é {type(a)}\n')          # \n para pular linha
print(f'Só tem espaços? {a.isspace()}')
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiúsculas? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
print(f'? {a.isidentifier()}')
print(f'É decimal? {a.isdecimal()}')
print(f'É digito? {a.isdigit()}')
print(f'Posso mostrar? {a.isprintable()}')